
export enum SortPomodoroEnum {
  START_RECENT = "START_RECENT",
  START_OLDEST = "START_OLDEST",
  LAST_MODIFIED = "LAST_MODIFIED",
  "CREATION_OLDEST" = "CREATION_OLDEST",
  "CREATION_RECENT" = "CREATION_RECENT",
}
